import PropTypes from 'prop-types';
import { Box, Link, Skeleton, Typography } from '@mui/material';
import { useTranslation } from 'react-i18next';
import AutoAwesomeOutlinedIcon from '@mui/icons-material/AutoAwesomeOutlined';
import * as tokens from '../../theme/tokens.js';

/**
 * An AI summary: a headline, an explanation and numbered recommendations. When `refOf`/`onShowRef`
 * are given, a recommendation that points at something on the page gets a "Show" link — only worth
 * it where that thing can be off screen (Library Quality's long issue list).
 */
const AiSummaryPanel = ({ insight, loading, onShowRef, refOf, testId = 'ai-summary' }) => {
	const { t } = useTranslation();
	if (!loading && !insight) return null;

	return (
		<Box sx={{ minWidth: 0 }} data-testid={testId}>
			<Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, mb: 0.75 }}>
				<AutoAwesomeOutlinedIcon sx={{ fontSize: tokens.iconSize.sm, color: tokens.brand.text }} />
				<Typography sx={{ fontSize: tokens.fontSize.caption, fontWeight: 700, color: tokens.ink.muted, textTransform: 'uppercase', letterSpacing: '0.07em' }}>
					{t('aiSummary.title', 'AI summary')}
				</Typography>
			</Box>

			{loading && !insight ? (
				<Box aria-label={t('aiSummary.loading', 'Writing the summary…')}>
					<Skeleton variant="text" width="70%" sx={{ fontSize: tokens.fontSize.body }} />
					<Skeleton variant="text" width="100%" />
					<Skeleton variant="text" width="90%" />
					<Skeleton variant="text" width="60%" />
				</Box>
			) : (
				<>
					<Typography sx={{ fontSize: tokens.fontSize.body, fontWeight: 700, color: tokens.ink.strong }}>
						{insight.headline}
					</Typography>
					{insight.explanation && (
						<Typography sx={{ fontSize: tokens.fontSize.body2, color: tokens.ink.body, mt: 0.5, lineHeight: 1.55 }}>
							{insight.explanation}
						</Typography>
					)}
					{insight.recommendations?.length > 0 && (
						<>
							<Typography sx={{ fontSize: tokens.fontSize.caption, fontWeight: 700, color: tokens.ink.muted, mt: 1.25, mb: 0.5 }}>
								{t('aiSummary.nextSteps', 'What to do next')}
							</Typography>
							<Box component="ol" sx={{ m: 0, pl: 2.5, display: 'flex', flexDirection: 'column', gap: 0.5 }}>
								{insight.recommendations.map((recommendation, index) => (
									<Typography component="li" key={index} sx={{ fontSize: tokens.fontSize.body2, color: tokens.ink.body }}>
										{recommendation.text}
										{refOf && onShowRef && refOf(recommendation) && (
											<Link
												component="button"
												type="button"
												onClick={() => onShowRef(refOf(recommendation))}
												sx={{ ml: 0.75, fontSize: tokens.fontSize.caption, fontWeight: 600, color: tokens.brand.text, verticalAlign: 'baseline' }}
											>
												{t('aiSummary.show', 'Show')}
											</Link>
										)}
									</Typography>
								))}
							</Box>
						</>
					)}
					<Typography sx={{ fontSize: tokens.fontSize.micro, color: tokens.ink.faintest, mt: 1 }}>
						{t('aiSummary.disclaimer', 'Generated by AI from the numbers on this page — check before acting.')}
					</Typography>
				</>
			)}
		</Box>
	);
};

AiSummaryPanel.propTypes = {
	insight: PropTypes.shape({
		headline: PropTypes.string,
		explanation: PropTypes.string,
		recommendations: PropTypes.arrayOf(PropTypes.shape({
			text: PropTypes.string,
		})),
	}),
	loading: PropTypes.bool,
	onShowRef: PropTypes.func,
	refOf: PropTypes.func,
	testId: PropTypes.string,
};

export default AiSummaryPanel;
