import PropTypes from 'prop-types';
import { Box, Link, Skeleton, Typography } from '@mui/material';
import { useTranslation } from 'react-i18next';
import AutoAwesomeOutlinedIcon from '@mui/icons-material/AutoAwesomeOutlined';
import * as tokens from '../../../theme/tokens.js';

/** The AI reading of the report: what it says and what to do, with a link to each matching issue. */
const QualityInsightPanel = ({ insight, loading, onShowIssue }) => {
	const { t } = useTranslation();
	if (!loading && !insight) return null;

	return (
		<Box sx={{ minWidth: 0 }} data-testid="quality-insight">
			<Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, mb: 0.75 }}>
				<AutoAwesomeOutlinedIcon sx={{ fontSize: tokens.iconSize.sm, color: tokens.brand.text }} />
				<Typography sx={{ fontSize: tokens.fontSize.caption, fontWeight: 700, color: tokens.ink.muted, textTransform: 'uppercase', letterSpacing: '0.07em' }}>
					{t('libraryQuality.insight.title', 'AI summary')}
				</Typography>
			</Box>

			{loading && !insight ? (
				<Box aria-label={t('libraryQuality.insight.loading', 'Writing the summary…')}>
					<Skeleton variant="text" width="70%" sx={{ fontSize: tokens.fontSize.body }} />
					<Skeleton variant="text" width="100%" />
					<Skeleton variant="text" width="90%" />
					<Skeleton variant="text" width="60%" />
				</Box>
			) : (
				<>
					<Typography sx={{ fontSize: tokens.fontSize.body, fontWeight: 700, color: tokens.ink.strong }}>
						{insight.headline}
					</Typography>
					{insight.explanation && (
						<Typography sx={{ fontSize: tokens.fontSize.body2, color: tokens.ink.body, mt: 0.5, lineHeight: 1.55 }}>
							{insight.explanation}
						</Typography>
					)}
					{insight.recommendations?.length > 0 && (
						<>
							<Typography sx={{ fontSize: tokens.fontSize.caption, fontWeight: 700, color: tokens.ink.muted, mt: 1.25, mb: 0.5 }}>
								{t('libraryQuality.insight.nextSteps', 'What to do next')}
							</Typography>
							<Box component="ol" sx={{ m: 0, pl: 2.5, display: 'flex', flexDirection: 'column', gap: 0.5 }}>
								{insight.recommendations.map((recommendation, index) => (
									<Typography component="li" key={index} sx={{ fontSize: tokens.fontSize.body2, color: tokens.ink.body }}>
										{recommendation.text}
										{recommendation.issueKey && (
											<Link
												component="button"
												type="button"
												onClick={() => onShowIssue(recommendation.issueKey)}
												sx={{ ml: 0.75, fontSize: tokens.fontSize.caption, fontWeight: 600, color: tokens.brand.text, verticalAlign: 'baseline' }}
											>
												{t('libraryQuality.insight.show', 'Show')}
											</Link>
										)}
									</Typography>
								))}
							</Box>
						</>
					)}
					<Typography sx={{ fontSize: tokens.fontSize.micro, color: tokens.ink.faintest, mt: 1 }}>
						{t('libraryQuality.insight.disclaimer', 'Generated by AI from the numbers on this page — check before acting.')}
					</Typography>
				</>
			)}
		</Box>
	);
};

QualityInsightPanel.propTypes = {
	insight: PropTypes.shape({
		headline: PropTypes.string,
		explanation: PropTypes.string,
		recommendations: PropTypes.arrayOf(PropTypes.shape({
			text: PropTypes.string,
			issueKey: PropTypes.string,
		})),
	}),
	loading: PropTypes.bool,
	onShowIssue: PropTypes.func.isRequired,
};

export default QualityInsightPanel;
